//Rubic!

//World
// Platform = x
// Lava = !
// Floater = y


//Actors
//Player = @
//Coin = o
//Key = k
//FALLING Lava SLOW = v
//bouncing Lava UP & DOWN fast = |
//Lava moving SIDEWAYS = =
//Slower SIDES = m
//Slower UP & DOWN = w
var GAME_LEVELS = [
  ["                                                                                    x  ",
   "                                                                                    x  ",
   "                                                                                    x  ",
   "                                                                                    x  ",
   "                                                                                    x  ",
   "                                                                                    x  ",
   "                                                                                    x  ",
   "                                                                                    x  ",
   "                                                xxxx                                x  ",
   " xxxxx x   x xx   xx xxxxx x                       x                                x  ",
   "   x   x   x x x x x x   x x                       x                                x  ",
   "   x   x   x x  x  x xxxx  x                xxx    x                                x  ",
   "   x   x   x x     x x              m              x                                x  ",
   " xx     xxx  x     x x     x                       x                                x  ",
   "                                     xxx           x                                x  ",
   "                                                   x                                x  ",
   "                                                   x                                x  ",
   "                                xxxx               x                                x  ",
   "                                                   x                            k   x  ",
   "                                                   x                  xxxxxxx       x  ",
   "                xxxxxx    xxxxxxxxxxxxxxx                             xxxxxxxxxxxxxxx  ",
   "              xxx    x!!!!x             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                ",
   "                x    x!!!!x             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                ",
   "                x    xxxxxx             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                ",
   "     @          x                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                ",
   "xxxxxxxxxxxxxxxxx                                                                      ",
   "                                                                                       "],
  ["       x                                                                                      x          ",
   "       x    xxxx  xxx  x    x    xxxx xxxx xxxxx                                              x          ",
   " @     x    x    x!!!x x    x    x    x      x                                                x          ",
   "xxx    x    x    x!!!x x    x    xxx  x      x                                                x          ",
   "       x    x    x!!!x x    x    x    x      x                                                x          ",
   "       x    xxxx  xvx  xxxx xxxx xxxx xxxx   x                                                x          ",
   "     o x                                                                                      x          ",
   "    xxxx                                                                                      x          ",
   "       x                                   w                                                  x          ",
   "       x                                                                                      x          ",
   "       x                                                                                      x          ",
   "       x                                                                        o             x          ",
   " o     x                    m           xxxxxx                               o     o          x          ",
   "xxx    x                                x    x                                                x          ",
   "                                        x    x                                             o  x          ",
   "                  xxxxxx         xxxxxxxx    x                         xxxxxx        xxxxxxxxxx          ",
   "                  x    x!!!!!!!!!x           x                         x    x!!!!!!!!x                   ",
   "                 xx    x!!!!!!!!!x!!!!!!!!!! xx        o  o  o        xx!!!!x!!!!!!!!x                   ",
   "                  x    x!!!!!!!!!!!!!!!!!!!!!            =             !!!!!!!!!!!!!!x                   ",
   "             o o ox    x!!!!!!!!!!!!!!!!!!!!xxo o        m          o xx!!!!!!!!!!!!!x                   ",
   "xxxxxxxxxxxxxxxxxxx    x!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!x                   ",
   "                       x!!!!!!!!!!!!!!!!!!!!x                          x!!!!!!!!!!!!!x                   "],
  ["                                                                                                                                                                                                ",
   "                      x              xxxx  x  x  xxx   xxx   xxx xxxx            x                                                                                                              ",
   "                     xx              x     x  x x   x x   x x    x               xx                                                                                                             ",
   "                    xxxxxxxx         x     xxxx x   x x   x  xx  xxx        xxxxxxxx                                                                                                            ",
   "                     xx              x     x  x x   x x   x    x x               xx                                                                                                             ",
   "                      x              xxxx  x  x  xxx   xxx  xxx  xxxx            x                                                                                                              ",
   "                                                                                                                                                                                                ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                   ",
   " x                                                                                                          x                                                                                   ",
   " x                                                                                                          x                                                                                   ",
   " x                           o                                                                              x                                                                                   ",
   " x                                                                                                          x                                                                                   ",
   " x           o  o  o                                   @                                                    x                                                                                   ",
   " x           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x                                                                                   ",
   " x           x                                                                                  x           x                                                                                   ",
   " x           x                                                                                  x           x                                                                                   ",
   " x           x                                                                       o          x           x                                                                                   ",
   " x           x              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        x           x                                       xxx                                         ",
   " x           x            o x                   =                                      x        x           x                                      x   x                                        ",
   " x           x          xxxxx                                            o             x        x           x                                          x                                        ",
   " x           x              x                               =               o          x        x           x                                         x                                         ",
   " x           x  o                                                      xxxxxxxx        x        x           x                                        x                                          ",
   " x           x                                              o   o      x             xxx        x           x                                        x                                          ",
   " x           xxxxxx                                       xxxxxxxxxxx            m     x        x           x                                                                                   ",
   " x           x                                                                         x        x           x                                        x                                          ",
   " x           x                                   o                                   o x        x           x                                                                                   ",
   " x           x                                            |                        xxxxx        x           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   " x           x            xxxxxxxx           xxxxxxx                                   x        x                                                                                             x ",
   " x           xo   |                      m         x                                o  x   o    x                                                                                             x ",
   " x           xxx       |                 o                                             x      x!x                                                                                             x ",
   " x           x                       xxxxxx        w                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                      x ",
   " x           x           x                                                                                  x          x                                                                      x ",
   " x           x!!!!!!!!!!!xx              |        xx         xxxxxxxxxxxxxx                                 x          x                                                                      x ",
   " x           x!!!!!!!!!!!xxx         |            x           x!!!!!!!!!!!     =                            x          x                                                                      x ",
   " x           x!!!!!!!!!!!xxxx                     x           x!!!!!!!!!!xxx                                x          x                                                                      x ",
   " x           x!!!!!!!!!!!xxxxx                    x           x!!!!!!!!!!!                =                 x          xxxxxx         xxxxxx         xxxxxx          xxxxxx           xxxxxxxxx ",
   " x           x!!!!!!!!!!!xxxxxx o              o  x    m      x!!!!!!!!!!xxxx                               x               x         x    x         x    x          x    x           x         ",
   " x           xxxvxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxx    |      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        ox               x         x    x         x    x          x    x           x         ",
   " x                                      |                                                                 xxx               x         x    x         x    x          x    x           x         ",
   " x                          |                                    o             |                            x               x         x    x         x    x          x    x           x         ",
   " x     o           o           o     o             xxx     xxx         |     o                              x               x         x    x         x    x          x    x           x         ",
   " x                                |               xxxx!!!!!xxxx            |                                x               x         x    x         x    x          x    x           x         ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               x         x    x         x    x          x    x           x         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               x         x    x         x    x          x    x           x         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               x         x    x         x    x          x    x           x         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               x         x    x         x    x          x    x           x         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               x         x    x         x    x          x    x           x         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               x         x    x         x    x          x    x           x         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               x         x    x         x    x    k     x    x           x         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               x!!!!!!!!!x    x!!!!!!!!!x    x          x    x!!!!!!!!!!!x         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               x!!!!!!!!!x    x!!!!!!!!!x    xxxxxxxxxxxx    x!!!!!!!!!!!x         "],
  ["               x                                                                                  x           ",
   "               x           xxxx  xxx  xx   xx xxxxx       xxx  x   x xxxxx xxxx    x              x           ",
   "               x          x     x   x x x x x x          x   x x   x x     x   x   x              x           ",
   "               x          x xxx xxxxx x  x  x xxx        x   x x   x xxx   xxxx    x              x           ",
   "               x          x   x x   x x     x x          x   x  x x  x     x  x                   x           ",
   "               x          xxxx  x   x x     x xxxxx       xxx    x   xxxxx x   x   x              x           ",
   "               x                                                                                  x           ",
   "               x                                                                                  x           ",
   "               x                                                                                  x           ",
   "               x   @                                                                         k    x           ",
   "               x                                                                                  x           ",
   "               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
